# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170413_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='digest_prefs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='message_prefs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='opt_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='scholar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watched_tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
